# Generated by Django 5.0.3 on 2024-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Sent", "Sent"),
                    ("Failed", "Failed"),
                ],
                max_length=50,
            ),
        ),
    ]
